chore: update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,17 +11,21 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
 
       - name: Extract directories
         id: extract_dirs
         run: |
           TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///'
+          FOLDER=$(echo $TAG_NAME | sed 's/^[^\/]*\///')
           # Extract the second and third directories from the tag name
           CODENAME=$(echo $TAG_NAME | cut -d'/' -f2)
+          PACKAGE_NAME=$(echo $TAG_NAME | cut -d'/' -f3)
           # ARCH=$(echo $TAG_NAME | cut -d'/' -f3)
           echo "::set-output name=codename::$CODENAME"
+          echo "::set-output name=package_name::PACKAGE_NAME"
+          echo "::set-output name=folder::FOLDER"
           # echo "::set-output name=arch::$ARCH"  
 
       - name: Sbuild setup
@@ -88,33 +92,28 @@ jobs:
           cd ${{ needs.extract_dirs.outputs.tag_name }}
           ${HOME}/.local/bin/pkg-builder verify  --no-package true
 
-    # Add any build steps here
+      - name: upload cleanup
+        run: | 
+          rm -rf /home/runner/.pkg-builder/packages/${{needs.extract_dirs.outputs.codename}}/${{needs.extract_dirs.outputs.package-name}}/${{needs.extract_dirs.outputs.package-name}}-1.0.0
+         # copy pkg-builder configs to artifacts
+          cd /home/runner/.pkg-builder/packages/${{needs.extract_dirs.outputs.codename}}/${{needs.extract_dirs.outputs.package-name}}
+          cp ${{ needs.extract_dirs.outputs.tag_name }}/pkg-builder.toml .
+          cp ${{ needs.extract_dirs.outputs.tag_name }}/pkg-builder-verify.toml .
+          rm *:*
+          rm *dbgsym* || true # possible there is none
 
-  create_release:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
       - name: Create Release
         id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        uses: actions/create-release@v4
         with:
           tag_name: ${{ github.ref }}
           release_name: Release ${{ github.ref }}
           draft: false
           prerelease: false
 
-  upload_assets:
-    runs-on: ubuntu-latest
-    needs: create_release
-    steps:
-      - name: Upload Assets
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # This should come after verify, but sometimes it is good to have it, to check why the verify fails
+      - name: Save results
+        uses: actions/upload-artifact@v4
         with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./path/to/artifact
-          asset_name: artifact.zip
-          asset_content_type: application/zip
+          name: ${{inputs.ref }}
+          path: /home/runner/.pkg-builder/packages/${{needs.extract_dirs.outputs.codename}}/${{needs.extract_dirs.outputs.package-name}}
